logo: "/images/profile.png?raw=true"
title: Miguel Castañeda
description: >
  ![Profile Picture](/images/profile.png?raw=true)  
  ## Miguel Castañeda  
  MBA | Junior Data Analyst | BI & Data Insights  
  UPC | Barcelona  

  **Project Tools:**  
  Excel, SQL, and Tableau  

  ### About Me:  
  MBA graduate with Data Analyst experience and over 4 years of experience in Business.  

  [View My LinkedIn Profile](https://www.linkedin.com/in/miguelcb7)  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
